# Generated by Django 5.2 on 2025-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_day',
            field=models.DateField(auto_now=True),
        ),
    ]
