# Generated by Django 5.2 on 2025-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventmodel_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_day',
            field=models.DateTimeField(),
        ),
    ]
