# Generated by Django 5.2 on 2025-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventmodel_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_day',
            field=models.DateField(),
        ),
    ]
